import yt_dlp
import os
import zipfile
import shutil
import re
import platform
import static_ffmpeg
from concurrent.futures import ThreadPoolExecutor
from database import log_download

DOWNLOADS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "temp_downloads"))

progress_store = {}

MAX_CONCURRENT_DOWNLOADS = 5
executor = ThreadPoolExecutor(max_workers=MAX_CONCURRENT_DOWNLOADS)


class MyLogger(object):
    def debug(self, msg):
        pass
    def warning(self, msg):
        pass
    def error(self, msg):
        print("YT-DLP ERROR:", msg)


def sanitize_filename(filename: str) -> str:
    return re.sub(r'[^\w\-\.\s\u0600-\u06FF]', '_', filename).strip()


# ─────────────────────────────────────────────────────────────────────────────
# Cookie file builder
# ─────────────────────────────────────────────────────────────────────────────
REQUIRED_YT_COOKIES = [
    'SAPISID', '__Secure-1PAPISID', '__Secure-3PAPISID',
    'SID', '__Secure-1PSID', '__Secure-3PSID',
    'SSID', 'HSID', 'APISID',
    'LOGIN_INFO', 'PREF', 'YSC', 'VISITOR_INFO1_LIVE',
]


def build_temp_cookie_file(cookies_str: str, task_id: str, output_dir: str) -> str:
    """
    Convert a raw browser cookie string  (key=val; key2=val2 ...)
    into a proper Netscape HTTP Cookie File for yt-dlp.

    Key fixes vs the previous version:
    - Uses split('=', 1) so base64 values containing '=' are preserved.
    - All cookies are marked Secure TRUE (required for __Secure-* names).
    - Fields are separated by a real TAB character (\\t).
    - Header is the exact string yt-dlp expects.
    """
    os.makedirs(output_dir, exist_ok=True)
    cookie_path = os.path.join(output_dir, f"yt_cookies_{task_id[:8]}.txt")

    parsed = {}
    for item in cookies_str.split(';'):
        item = item.strip()
        if not item or '=' not in item:
            continue
        name, value = item.split('=', 1)   # split on FIRST '=' only
        name  = name.strip()
        value = value.strip()
        if name:
            parsed[name] = value

    lines = ["# Netscape HTTP Cookie File", "# Generated by MiGo", ""]
    for name, value in parsed.items():
        # domain  include_subdomains  path  secure  expiry  name  value
        lines.append(f".youtube.com\tTRUE\t/\tTRUE\t2099999999\t{name}\t{value}")

    with open(cookie_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    found   = [k for k in REQUIRED_YT_COOKIES if k in parsed]
    missing = [k for k in ['SAPISID', '__Secure-3PAPISID', 'SID'] if k not in parsed]
    print(f"[MiGo] Cookie file: {len(parsed)} entries | present={found} | missing={missing}")

    return cookie_path


# ─────────────────────────────────────────────────────────────────────────────
# Shared base options
# ─────────────────────────────────────────────────────────────────────────────
def _base_ydl_opts(cookie_file: str, extra: dict = None) -> dict:
    opts = {
        'quiet':       True,
        'no_warnings': True,
        'cookiefile':  cookie_file,
        'logger':      MyLogger(),
        'user_agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/125.0.0.0 Safari/537.36'
        ),
        'extractor_args': {
            'youtube': {
                'player_client': ['web', 'android'],
            }
        },
    }
    ffmpeg_path = shutil.which('ffmpeg')
    if ffmpeg_path:
        opts['ffmpeg_location'] = ffmpeg_path
    if extra:
        opts.update(extra)
    return opts


# ─────────────────────────────────────────────────────────────────────────────
# Media info  (now also accepts user cookies so YT info-fetch works)
# ─────────────────────────────────────────────────────────────────────────────
def get_media_info(url: str, cookies: str = None):
    static_ffmpeg.add_paths()

    tmp_cookie_path = None
    cookie_file     = 'cookies.txt'

    if cookies and cookies.strip():
        tmp_dir = os.path.join(DOWNLOADS_DIR, "_info_tmp")
        os.makedirs(tmp_dir, exist_ok=True)
        import uuid as _uuid
        try:
            tmp_cookie_path = build_temp_cookie_file(cookies, _uuid.uuid4().hex[:8], tmp_dir)
            cookie_file     = tmp_cookie_path
        except Exception as ce:
            print(f"[MiGo] Info cookie write failed: {ce}")

    ydl_opts = _base_ydl_opts(cookie_file, {'extract_flat': 'in_playlist'})

    def _cleanup():
        if tmp_cookie_path and os.path.exists(tmp_cookie_path):
            try:
                os.remove(tmp_cookie_path)
            except:
                pass

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
        _cleanup()

        if 'entries' in info:
            return {
                'type':          'playlist',
                'title':         info.get('title', 'Playlist'),
                'videos': [
                    {'title': e.get('title', f'Video {i+1}'),
                     'url': e.get('url'), 'id': e.get('id')}
                    for i, e in enumerate(info['entries'])
                ],
                'qualities':     ['144p', '240p', '360p', '480p', '720p', '1080p', '1440p', '2160p'],
                'audio_options': ['best'],
                'subtitles':     [],
            }

        video_heights = {
            int(f['height'])
            for f in info.get('formats', [])
            if f.get('vcodec') != 'none' and f.get('height')
        }
        all_subs = set(
            list(info.get('subtitles', {}).keys()) +
            list(info.get('automatic_captions', {}).keys())
        )
        return {
            'type':          'video',
            'title':         info.get('title', 'Video'),
            'thumbnail':     info.get('thumbnail'),
            'qualities':     [f"{h}p" for h in sorted(video_heights)] or ['best'],
            'audio_options': ['best'],
            'subtitles':     sorted(all_subs),
        }

    except Exception as e:
        _cleanup()
        raw = str(e).lower()
        if "private video" in raw:
            return {"error": "هذا الفيديو خاص (Private)"}
        if "unsupported url" in raw:
            return {"error": "الرابط غير مدعوم أو غير صحيح"}
        if "sign in" in raw or "login" in raw or "age" in raw:
            return {
                "error": (
                    "يوتيوب يطلب تسجيل الدخول — "
                    "الرجاء لصق كوكيز يوتيوب في الحقل المخصص ثم اضغط «جلب البيانات» مجدداً."
                )
            }
        return {"error": f"خطأ: {e}"}


# ─────────────────────────────────────────────────────────────────────────────
# Download task
# ─────────────────────────────────────────────────────────────────────────────
def download_media_task(task_id: str, url: str, dl_type: str,
                        quality: str, lang: str = None, cookies: str = None):
    output_dir = os.path.join(DOWNLOADS_DIR, task_id)
    os.makedirs(output_dir, exist_ok=True)

    cookie_file      = 'cookies.txt'
    temp_cookie_path = None

    if cookies and cookies.strip():
        try:
            temp_cookie_path = build_temp_cookie_file(cookies, task_id, output_dir)
            cookie_file      = temp_cookie_path
        except Exception as ce:
            print(f"[MiGo] Download cookie write failed: {ce}")

    ansi_re = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')

    def hook_wrapper(d):
        def clean(s): return ansi_re.sub('', str(s)).strip()
        if d['status'] == 'downloading':
            progress_store[task_id] = {
                "status":   "downloading",
                "percent":  clean(d.get('_percent_str', '0.0%')),
                "speed":    clean(d.get('_speed_str',   '0 KiB/s')),
                "eta":      clean(d.get('_eta_str',     '0s')),
                "filename": os.path.basename(d.get('filename', '')),
            }
        elif d['status'] == 'finished':
            progress_store[task_id] = {
                "status": "processing", "percent": "100%",
                "speed": "0 KiB/s", "eta": "0s",
                "filename": "Merging / Finalizing…",
            }

    ydl_opts = _base_ydl_opts(cookie_file, {
        'outtmpl':          os.path.join(output_dir, '%(title).100s.%(ext)s'),
        'progress_hooks':   [hook_wrapper],
        'quiet':            False,
        'windowsfilenames': True,
    })

    # Local ffmpeg override
    local_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    if platform.system() == "Windows" and os.path.exists(os.path.join(local_root, "ffmpeg.exe")):
        ydl_opts['ffmpeg_location'] = local_root
    elif platform.system() != "Windows" and os.path.isfile(os.path.join(local_root, "ffmpeg")):
        ydl_opts['ffmpeg_location'] = local_root

    if dl_type == 'video':
        h = quality.replace('p', '') if quality != 'best' else None
        ydl_opts['format'] = (
            'bestvideo+bestaudio/best' if not h
            else f'bestvideo[height<={h}]+bestaudio/best[height<={h}]/best'
        )
        ydl_opts['merge_output_format'] = 'mp4'

    elif dl_type == 'audio':
        ydl_opts['format'] = 'bestaudio/best'
        ydl_opts['postprocessors'] = [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }]

    elif dl_type == 'subtitle':
        ydl_opts['skip_download']     = True
        ydl_opts['writesubtitles']    = True
        ydl_opts['writeautomaticsub'] = True
        ydl_opts['subtitleslangs']    = [lang] if lang else ['en']

    is_playlist = False
    try:
        with yt_dlp.YoutubeDL({'quiet': True, 'extract_flat': 'in_playlist',
                                'cookiefile': cookie_file}) as chk:
            info_chk = chk.extract_info(url, download=False)
            if info_chk and 'entries' in info_chk:
                is_playlist = True
                ydl_opts['outtmpl'] = os.path.join(
                    output_dir, '%(playlist_index)s - %(title)s.%(ext)s')
    except:
        pass

    def run_download():
        progress_store[task_id] = {
            "status": "starting", "percent": "0%",
            "speed": "", "eta": "", "filename": "",
        }
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])

            files = [f for f in os.listdir(output_dir)
                     if not f.startswith('yt_cookies_')]

            if not files:
                msg = "لم يتم تحميل أي ملفات. قد لا توجد ترجمات متاحة."
                progress_store[task_id] = {"status": "error", "error": msg}
                log_download("Railway_Server", task_id, url, "No Files",
                             dl_type, quality, False, msg)
                return

            if len(files) > 1 or is_playlist:
                zip_name = f"playlist_{task_id[:8]}.zip"
                zip_path = os.path.join(DOWNLOADS_DIR, zip_name)
                with zipfile.ZipFile(zip_path, 'w') as zf:
                    for root, _dirs, fs in os.walk(output_dir):
                        for fname in fs:
                            if fname.startswith('yt_cookies_'):
                                continue
                            zf.write(os.path.join(root, fname),
                                     sanitize_filename(fname))
                progress_store[task_id] = {
                    "status": "completed", "file_path": zip_path, "filename": zip_name}
            else:
                orig     = files[0]
                safe     = sanitize_filename(orig)
                dst_path = os.path.join(DOWNLOADS_DIR, f"{task_id[:8]}_{safe}")
                os.rename(os.path.join(output_dir, orig), dst_path)
                progress_store[task_id] = {
                    "status": "completed", "file_path": dst_path, "filename": safe}

            log_download("Railway_Server", task_id, url, "Success",
                         dl_type, quality, True)
            shutil.rmtree(output_dir, ignore_errors=True)

        except Exception as e:
            raw = str(e).lower()
            if "private video" in raw:
                friendly = "هذا الفيديو خاص (Private)"
            elif "ffmpeg is not installed" in raw:
                friendly = "FFmpeg غير موجود على الخادم"
            elif "sign in" in raw or "login" in raw or "age" in raw:
                friendly = (
                    "يوتيوب لا يزال يطلب تسجيل الدخول. "
                    "تأكد من لصق هذه الكوكيز تحديداً: "
                    "SAPISID, __Secure-3PAPISID, SID, SSID, HSID"
                )
            else:
                friendly = f"حدث خطأ أثناء التحميل: {e}"

            log_download("Railway_Server", task_id, url, "Failed",
                         dl_type, quality, False, str(e))
            progress_store[task_id] = {"status": "error", "error": friendly}
            shutil.rmtree(output_dir, ignore_errors=True)

    executor.submit(run_download)
